# app/exceptions/__init__.py
from .db import DatabaseConnectionError

__all__ = ["DatabaseConnectionError"]
